### ISSUE TITLE
AirBnB login broken

### ISSUE THREAD

**Issue by LinusU** [buttercup/locust#14]
It seems like the AirBnB login form is using some rendering framework that doesn't pick up the way we change the value of the input. I've tried executing the code manually, and the inputted values first show up in the form, but when `submitButton.click()` is executed, the form gets rerendered with empty inputs and an error below each of them.

<img width="542" alt="screen shot 2018-01-22 at 17 06 01" src="https://user-images.githubusercontent.com/189580/35233701-c469093a-ff96-11e7-9b92-058894898733.png">

I'll continue to investigate and update this issue with my findings...

**Comment by LinusU** [comment]
So, after a ton of digging I think I'm on to something:

https://stackoverflow.com/a/46012210/148072

https://github.com/cypress-io/cypress/issues/647#issuecomment-335829482

I'll send a PR shortly

**Comment by perry-mitchell** [comment]
Thanks @LinusU! So I initially got worried that it's a React thing, due to how it handles keystroke events, but some examples like [this](http://saga-login-flow.surge.sh/login) still work (using React).

**Comment by LinusU** [comment]
I've submitted #15 with a few tricks: make sure the events bubble (I think react sometimes just listens higher up to reduce the number of listeners), fire first `input`, and then a `changed` event (this is what happens when using the keyboard to e.g. paste in a password) and finally; use the native `value`-setter (seems like React overrides this with something and for some reason that doesn't work 😕)

**Comment by perry-mitchell** [comment]
@LinusU Thanks for the awesome PR! Worked well during tests and I've confirmed that at least for me the behaviour changed on the AirBNB login page. I'll now release a new version.

**Comment by perry-mitchell** [comment]
With regards to the extra effort to set the field values: Nothing surprises me here, especially with what's required to get it to work with React. Glad you found a solution.
