### ISSUE TITLE
Support Uber login form

### ISSUE THREAD

**Issue by LinusU** [buttercup/locust#21]
link: https://auth.uber.com/login/

The username input field could be caught by `[id=useridInput]`, but the password field isn't visible until the next button is pressed.

Currently, Locust doesn't detect a login target at all for me.

```html
<input type="text" class="text-input" placeholder="Email address or mobile number" value="" id="useridInput" autocorrect="off" autocapitalize="off" name="textInputValue" aria-required="true" aria-invalid="false" aria-describedby="error-caption input-title" data-reactid="20">
```

**Comment by perry-mitchell** [comment]
Moved to grouped issue: buttercup/locust#27
