### ISSUE TITLE
Consider using `form.elements`

### ISSUE THREAD

**Issue by LinusU** [buttercup/locust#22]
In some pages, that probably isn't technically proper HTML, the form tag can be prematurely closed and not have any children. In this case, there will still be `input`-elements linked to the form, and the form will submit just fine. However, using `querySelectorAll` on the form will always result in an empty result-set, since the form has no children.

It would be interesting to investigate an approach where we look at `form.elements` (which will hold all the inputs linked to the form) instead of using `querySelectorAll` on the form.

example site: http://www.aavtrain.com/create_user.asp

**Comment by perry-mitchell** [comment]
This could most likely be accomplished by, as you said, using `form.elements` and then running [`Element.matches`](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches) over all the items.

**Comment by perry-mitchell** [comment]
Looking further into this, I think that sites such as moje.axa.cz (mentioned recently) have a form and elements but they're not linked - it's a good example that we need to remove our dependence on `<form>`s altogether. I'll close this in favour of a new issue: #33
