### ISSUE TITLE
Webdav connexion error

### ISSUE THREAD

**Issue by wonao** [buttercup/locust#41]
Hi, 
I just discover your tool for managing password locally. Connexion to webdav worked perfectly with desktop app, android apps and chrome plugin... But firefox is not connecting to the same webdav server and ids than the other. Here is the error code I recevied : 
Failed connecting to 'webdav' resource
A connection attempt to 'https://acloud2.zaclys.com/remote.php/dav/files/10970/' has failed: Request failed with status code 401
I tried each version since 2.24.2. but each verison is giving same result. I tried the main version on another computer on windows 11 and it's the same problem.
Is someone can help me ?

**Comment by perry-mitchell** [comment]
Wrong repository for this. Should be either on the desktop app or the WebDAV library we use.

Either way this is most likely either a limitation of your WebDAV provider or you're using the wrong credentials.

Often times storage hosting providers provide alternative login credentials for WebDAV endpoints, so you should look into that. 401 indicates that the endpoint does not think it received any credentials so it's possible that they don't support standard basic authentication. You should contact them and ask, or try to find documentation on the matter. If they don't support basic dav auth then they're simply not supported by buttercup.

I'll gladly reopen this if there's something we can do on our side but I doubt that's the case.
