### ISSUE TITLE
Add support for github login form

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/locust#5]
HTML:
![image](https://user-images.githubusercontent.com/3869469/35117820-766e1154-fc98-11e7-8c75-3d5c44e0fab3.png)

Neither the username field nor the password field are detected.

**Comment by LinusU** [comment]
> [...] nor the password field are detected.

Sure about this? It seems like the original bug mentioned that the password field worked, but not the username.

Seems like it should work:

https://github.com/buttercup/locust/blob/fc340a425440ac4f4f1b2ad43076f7608b798143/source/inputPatterns.js#L5-L6

**edit:** just confirmed that it fills password but not username, I have a fix for it as well, submitting soon™
